
export const WCAG_REFERENCE = {
    "1.1.1 - Non-text Content (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.1.1",
    "1.2.1 - Audio-only and Video-only (Prerecorded) (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.1",
    "1.2.2 - Captions (Prerecorded) (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.2",
    "1.2.3 - Audio Description or Media Alternative (Prerecorded) (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.3",
    "1.2.4 - Captions (Live) (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.4",
    "1.2.5 - Audio Description (Prerecorded) (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.5",
    "1.2.6 - Sign Language (Prerecorded) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.6",
    "1.2.7 - Extended Audio Description (Prerecorded) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.7",
    "1.2.8 - Media Alternative (Prerecorded) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.8",
    "1.2.9 - Audio-only (Live) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.2.9",
    "1.3.1 - Info and Relationships (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.3.1",
    "1.3.2 - Meaningful Sequence (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.3.2",
    "1.3.3 - Sensory Characteristics (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.3.3",
    "1.3.4 - Orientation (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.3.4",
    "1.3.5 - Identify Input Purpose (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.3.5",
    "1.3.6 - Identify Purpose (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.3.6",
    "1.4.1 - Use of Color (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.1",
    "1.4.10 - Reflow (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.10",
    "1.4.11 - Non-text Contrast (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.11",
    "1.4.12 - Text Spacing (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.12",
    "1.4.13 - Content on Hover or Focus (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.13",
    "1.4.2 - Audio Control (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.2",
    "1.4.3 - Contrast (Minimum) (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.3",
    "1.4.4 - Resize text (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.4",
    "1.4.5 - Images of Text (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.5",
    "1.4.6 - Contrast (Enhanced) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.6",
    "1.4.7 - Low or No Background Audio (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.7",
    "1.4.8 - Visual Presentation (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.8",
    "1.4.9 - Images of Text (No Exception) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/5-principle-1/sc-1.4.9",
    "2.1.1 - Keyboard (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.1.1",
    "2.1.2 - No Keyboard Trap (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.1.2",
    "2.1.3 - Keyboard (No Exception) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.1.3",
    "2.1.4 - Character Key Shortcuts (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.1.4",
    "2.2.1 - Timing Adjustable (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.2.1",
    "2.2.2 - Pause, Stop, Hide (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.2.2",
    "2.2.3 - No Timing (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.2.3",
    "2.2.4 - Interruptions (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.2.4",
    "2.2.5 - Re-authenticating (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.2.5",
    "2.2.6 - Timeouts (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.2.6",
    "2.3.1 - Three Flashes or Below Threshold (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.3.1",
    "2.3.2 - Three Flashes (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.3.2",
    "2.3.3 - Animation from Interactions (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.3.3",
    "2.4.1 - Bypass Blocks (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.1",
    "2.4.10 - Section Headings (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.10",
    "2.4.2 - Page Titled (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.2",
    "2.4.3 - Focus Order (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.3",
    "2.4.4 - Link Purpose (In Context) (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.4",
    "2.4.5 - Multiple Ways (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.5",
    "2.4.6 - Headings and Labels (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.6",
    "2.4.7 - Focus Visible (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.7",
    "2.4.8 - Location (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.8",
    "2.4.9 - Link Purpose (Link Only) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.4.9",
    "2.5.1 - Pointer Gestures (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.5.1",
    "2.5.2 - Pointer Cancellation (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.5.2",
    "2.5.3 - Label in Name (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.5.3",
    "2.5.4 - Motion Actuation (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.5.4",
    "2.5.5 - Target Size (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.5.5",
    "2.5.6 - Concurrent Input Mechanisms (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/6-principle-2/sc-2.5.6",
    "3.1.1 - Language of Page (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.1.1",
    "3.1.2 - Language of Parts (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.1.2",
    "3.1.3 - Unusual Words (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.1.3",
    "3.1.4 - Abbreviations (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.1.4",
    "3.1.5 - Reading Level (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.1.5",
    "3.1.6 - Pronunciation (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.1.6",
    "3.2.1 - On Focus (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.2.1",
    "3.2.2 - On Input (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.2.2",
    "3.2.3 - Consistent Navigation (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.2.3",
    "3.2.4 - Consistent Identification (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.2.4",
    "3.2.5 - Change on Request (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.2.5",
    "3.3.1 - Error Identification (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.3.1",
    "3.3.2 - Labels or Instructions (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.3.2",
    "3.3.3 - Error Suggestion (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.3.3",
    "3.3.4 - Error Prevention (Legal, Financial, Data) (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.3.4",
    "3.3.5 - Help (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.3.5",
    "3.3.6 - Error Prevention (All) (Level AAA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/7-principle-3/sc-3.3.6",
    "4.1.1 - Parsing (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/8-principle-4/sc-4.1.1",
    "4.1.2 - Name, Role, Value (Level A)": "/KnowledgeCenter/Modules/wcag-w3c-reference/8-principle-4/sc-4.1.2",
    "4.1.3 - Status Messages (Level AA)": "/KnowledgeCenter/Modules/wcag-w3c-reference/8-principle-4/sc-4.1.3",
}

export const WCAG_TESTS = {
    "1.1.1 Non-text Content (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.1.1",
    "1.2.1 Audio-only and Video-only (Prerecorded) (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.1",
    "1.2.2 Captions (Prerecorded) (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.2",
    "1.2.3 Audio Description or Media Alternative (Prerecorded) (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.3",
    "1.2.4 Captions (Live) (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.4",
    "1.2.5 Audio Description (Prerecorded) (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.5",
    "1.2.6 Sign Language (Prerecorded) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.6",
    "1.2.7 Extended Audio Description (Prerecorded) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.7",
    "1.2.8 Media Alternative (Prerecorded) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.8",
    "1.2.9 Audio-only (Live) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.2.9",
    "1.3.1 Info and Relationships (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.3.1",
    "1.3.2 Meaningful Sequence (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.3.2",
    "1.3.3 Sensory Characteristics (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.3.3",
    "1.3.4 Orientation (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.3.4",
    "1.3.5 Identify Input Purpose (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.3.5",
    "1.3.6 Identify Purpose (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.3.6",
    "1.4.1 Use of Color (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.1",
    "1.4.10 Reflow (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.10",
    "1.4.11 Non-text Contrast (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.11",
    "1.4.12 Text Spacing (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.12",
    "1.4.13 Content on Hover or Focus (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.13",
    "1.4.2 Audio Control (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.2",
    "1.4.3 Contrast (Minimum) (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.3",
    "1.4.4 Resize Text (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.4",
    "1.4.5 Images of Text (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.5",
    "1.4.6 Contrast (Enhanced) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.6",
    "1.4.7 Low or No Background Audio (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.7",
    "1.4.8 Visual Presentation (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.8",
    "1.4.9 Images of Text (No Exception) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/1.4.9",
    "2.1.1 Keyboard (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.1.1",
    "2.1.2 No Keyboard Trap (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.1.2",
    "2.1.3 Keyboard (No Exception) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.1.3",
    "2.1.4 Character Key Shortcuts (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.1.4",
    "2.2.1 Timing Adjustable (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.2.1",
    "2.2.2 Pause, Stop, Hide (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.2.2",
    "2.2.3  No Timing (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.2.3",
    "2.2.4 Interruptions (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.2.4",
    "2.2.5 Re-authenticating (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.2.5",
    "2.2.6 Timeouts (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.2.6",
    "2.3.1 Three Flashes or Below Threshold (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.3.1",
    "2.3.2 Three Flashes (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.3.2",
    "2.3.3 Animation from Interactions (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.3.3",
    "2.4.1 Bypass Blocks (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.1",
    "2.4.10 Section Headings (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.10",
    "2.4.11 Focus Not Obscured (Minimum) (Level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.11",
    "2.4.12 Focus Not Obscured (Enhanced) (Level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.12",
    "2.4.13 Focus Appearance (Level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.13",
    "2.4.2 Page Titled (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.2",
    "2.4.3 Focus Order (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.3",
    "2.4.4 Link Purpose (In Context) (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.4",
    "2.4.5 Multiple Ways (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.5",
    "2.4.6 Headings and Labels (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.6",
    "2.4.7 Focus Visible (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.7",
    "2.4.8 Location (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.8",
    "2.4.9 Link Purpose (Link Only) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.4.9",
    "2.5.1 Pointer Gestures (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.1",
    "2.5.2 Pointer Cancellation (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.2",
    "2.5.3 Label in Name (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.3",
    "2.5.4 Motion Actuation (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.4",
    "2.5.5 Target Size (Enhanced) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.5",
    "2.5.6 Concurrent Input Mechanisms (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.6",
    "2.5.7 Dragging Movements (Level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.7",
    "2.5.8 Target Size (Minimum) (Level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/2.5.8",
    "3.1.1 Language of Page (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.1.1",
    "3.1.2 Language of Parts (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.1.2",
    "3.1.3 Unusual Words (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.1.3",
    "3.1.4 Abbreviations (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.1.4",
    "3.1.5 Reading Level (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.1.5",
    "3.1.6 Pronunciation (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.1.6",
    "3.2.1 On Focus (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.2.1",
    "3.2.2 On Input (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.2.2",
    "3.2.3 Consistent Navigation (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.2.3",
    "3.2.4 Consistent Identification (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.2.4",
    "3.2.5 Change on Request (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.2.5",
    "3.2.6 Consistent Help (Level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.2.6",
    "3.3.1 Error Identification (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.1",
    "3.3.2 Labels or Instructions (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.2",
    "3.3.3 Error Suggestion (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.3",
    "3.3.4 Error Prevention (Legal, Financial, Data) (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.4",
    "3.3.5 Help (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.5",
    "3.3.6 Error Prevention (All) (level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.6",
    "3.3.7 Redundant entry (Level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.7",
    "3.3.8 Accessible Authentication (Minimum) (Level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.8",
    "3.3.9 Accessible Authentication (Enhanced) (Level AAA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/3.3.9",
    "4.1.1 Parsing (Obsolete and removed) (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/4.1.1",
    "4.1.2 Name, Role, Value (level A)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/4.1.2",
    "4.1.3 Status Messages (level AA)": "/KnowledgeCenter/Modules/wcag-test-web/2-success-criteria/4.1.3",
}